<a href="https://colab.research.google.com/github/Doumgit/Souleymane-D-SQL-Week-1/blob/main/Math_with_Python%2C_Homework_2%2C_Student_Souleymane_Doumbia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **MATH** **WITH** **PYTHON**, **WEEK** **2**

SOULEYMANE DOUMBIA

**QUESTION 1:** Computing the eigenvalues and right eigenvectors of a given square array.

**First Option: To find eigevalues and eigenvectors of square matrix**

In [ ]:
# To compute  eigenvalues, you have to compute (A - lam@I)X = O which gives det(A - lam@I) = 0;
# by solving det(A - lam*I) = 0, we will get values of lam.
# To compute eigenvectors X, we use eigenvalues (lam) above; how? We know A@X = lam@X.
# 1st option: Then, we do raw echelon of ([A-lam]) and ([zeros matrix]);
# 2nd option: Then, we solve for [A - lam*I]@X = O which will gives X directly. 

from sympy import Symbol, solve, Matrix, eye, symbols
import numpy as np, numpy as geek
import scipy, scipy.linalg
from numpy import array

def get_eigenvalues ( in_arr ):
  '''
  Solve for Eigenvalues of any NxM matrix.
  '''

  # create matrix, A
  A = Matrix(in_arr)

  # create same size identity matrix, I
  I = eye( len (in_arr[ 0 ]))

  # put lambda on diagonal of identity matrix, LI
  L = Symbol( 'lambda' )
  LI = L * I
  
  A_LI = A - LI

  # compute |A - LI|
  det_A_LI = A_LI.det()
  

  # solve for |A - LI| = 0
  soln = solve(det_A_LI)

  return soln

try:
  numR = int(input("How many rows (ONLY ONE NUMBER):"))
  numC = int(input("How many columns (ONLY ONE NUMBER):"))
  numT = numR*numC
  
  if (numC == numR):
    print("Enter {0} entries in a single line (separated by space): ".format(numT))
    entries = list(map(int, input().split()))
    
    if (len(entries) == numT):
      matrix = np.array(entries).reshape(numR, numC)
      M = matrix
      print(' ')
      print('M =',M)
      print(' ')

      Eigenvalues_are = get_eigenvalues(M)
      print('eigenvalues are :',Eigenvalues_are) 

      # Finding Eigenvectors: M@X = Lambda@X ---> (M-Lambda)@X = b, with b = [0,0,0,...]

      Eigenvalues_are = np.array(Eigenvalues_are)
      d = np.identity(len(M),int)
      b = list(geek.zeros([len(M)], int))
      for i in Eigenvalues_are:
        c = np.array((i*d),int)
        exp = np.array((M - c),int)
        eig_V = np.linalg.inv(exp).dot(b)
        print(' ')
        print('For eigenvalue = {0} , eigenvector is {1}'.format(i, eig_V))

    else:
      print('Enter {0} entries separated by a space'.format(numR*numC))

  else:
    print("Enter an identical integer value")
    
except ValueError:
  print("ENTER A NUMBER")


# THIS OPTION GIVES ME MY EIGENVALUES OF ANY GIVEN SQUARE MATRIX
# BUT, IT DOES NOT GIVE ME A NON-ZERO EIGEINVECTORS UNLESS I CHANGE  b_entries > 0.


How many rows (ONLY ONE NUMBER):2
How many columns (ONLY ONE NUMBER):2
Enter 4 entries in a single line (separated by space): 
1 2 3 4
 
M = [[1 2]
 [3 4]]
 
eigenvalues are : [5/2 - sqrt(33)/2, 5/2 + sqrt(33)/2]
 
For eigenvalue = 5/2 - sqrt(33)/2 , eigenvector is [0. 0.]
 
For eigenvalue = 5/2 + sqrt(33)/2 , eigenvector is [0. 0.]


**Second Option: To find eigevalues and eigenvectors of square matrix**

In [ ]:
import numpy as np
from numpy.linalg import eig
  
try:
  numR = int(input("How many rows (ONLY ONE NUMBER):"))
  numC = int(input("How many columns (ONLY ONE NUMBER):"))
  numT = numR*numC
  
  if (numC == numR):
    print("Enter {0} entries in a single line (separated by space): ".format(numT))
    entries = list(map(int, input().split()))
    
    if (len(entries) == numT):
      matrix = np.array(entries).reshape(numR, numC)
      M = matrix
      print(' ')
      print('M =',M)
      print(' ')

      eigenvalues, eigenvectors = eig(M)
      print('eigenvalues = ',list(eigenvalues))
      print(' ')
      for i in range(len(eigenvalues)):
        print('For eigenvalue = {0}, eigenvector is {1}'.format(eigenvalues[i], eigenvectors[i,]))
        print(' ')

    else:
      print('Enter {0} entries separated by a space'.format(numR*numC))

  else:
    print("Enter an identical integer value")

except ValueError:
  print("ENTER A NUMBER")

# THIS OPTION GIVES ME MY EIGENVALUES OF ANY GIVEN SQUARE MATRIX
# IT ALSO DOES GIVE ME EIGEINVECTORS.
# THIS METHOD IS MY BEST METHOD

How many rows (ONLY ONE NUMBER):2
How many columns (ONLY ONE NUMBER):2
Enter 4 entries in a single line (separated by space): 
1 2 3 4
 
M = [[1 2]
 [3 4]]
 
eigenvalues =  [-0.3722813232690143, 5.372281323269014]
 
For eigenvalue = -0.3722813232690143, eigenvector is [-0.82456484 -0.41597356]
 
For eigenvalue = 5.372281323269014, eigenvector is [ 0.56576746 -0.90937671]
 


**QUESTION 2:** Computing the factor of a given array by Singular Value Decomposition

In [ ]:
import numpy as np
from numpy import array
from scipy.linalg import svd

# Defining singular-value decomposition function
def SVD_factor(A):
  print('Array A is:',A)
  print('')
  U, s, V = svd(A)
  print('Factors of array A by Singular Value Decomposition are: ')
  print('')
  print('U = ',U)
  print('')
  print('s = ',s)
  print('')
  print('V = ',V)

# Getting the array input from user (Matrix to factorise by SVD)
try:
  numR = int(input("How many rows:"))
  numC = int(input("How many columns:"))
  numT = numR * numC
  
  print("Enter {0} entries in a single line (SEPARATED BY SPACE): ".format(numT))
  entries = list(map(int, input().split()))
  print('')
  
  if len(entries) == numT:
    matrix = np.array(entries).reshape(numR, numC)
    M = matrix
    #print('M =',M)
    SVD_factor(M)
  else:
    print('Total entry should be {0}'.format(numT))

except ValueError:
  print("ENTER INTEGER VALUE ONLY")


How many rows:2
How many columns:3
Enter 6 entries in a single line (SEPARATED BY SPACE): 
1 2 3 4 5 6

Array A is: [[1 2 3]
 [4 5 6]]

Factors of array A by Singular Value Decomposition are: 

U =  [[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]]

s =  [9.508032   0.77286964]

V =  [[-0.42866713 -0.56630692 -0.7039467 ]
 [ 0.80596391  0.11238241 -0.58119908]
 [ 0.40824829 -0.81649658  0.40824829]]





**QUESTION 3:** Computing the determinant of a given array.

In Question 1 above, we were able to compute eigenvalues of 
a given square array in two ways. Since, the product of all eigenvalues of
a square matrix is the determinant of that matrix, therefore, we can use the codes above to compute determinant of a given array. 
We will apply here those two methods to find determinant of a given array:

First option:

In [60]:
from sympy import Symbol, solve, Matrix, eye, symbols
import numpy as np, numpy as geek
import scipy, scipy.linalg
from numpy import array

def get_eigenvalues ( in_arr ):
  A = Matrix(in_arr)
  I = eye( len (in_arr[ 0 ]))
  L = Symbol( 'lambda' )
  LI = L * I
  A_LI = A - LI
  det_A_LI = A_LI.det()
  soln = solve(det_A_LI)
  return soln

try:
  numR = int(input("How many rows (ONLY ONE NUMBER):"))
  numC = int(input("How many columns (ONLY ONE NUMBER):"))
  numT = numR*numC
  
  if (numC == numR):
    print("Enter {0} entries in a single line (separated by space): ".format(numT))
    entries = list(map(int, input().split()))
    print(' ')
    
    if (len(entries) == numT):
      matrix = np.array(entries).reshape(numR, numC)
      M = matrix
      #print('M =',M)

      eigenvalues = get_eigenvalues((M))
      print('Eigenvalues of array M: ',list(eigenvalues))
      print(' ')
       
    else:
      print('Enter {0} entries separated by a space'.format(numR*numC))

  else:
    print("Enter an identical integer value")
except ValueError:
  print("ENTER A NUMBER")

num = 1
for i in range(len(eigenvalues)):
  num *= eigenvalues[i]

print('Therefore determinant of Array M is: {0}'.format(num))

How many rows (ONLY ONE NUMBER):2
How many columns (ONLY ONE NUMBER):2
Enter 4 entries in a single line (separated by space): 
1 2 3 4
 
Eigenvalues of array M:  [5/2 - sqrt(33)/2, 5/2 + sqrt(33)/2]
 
Therefore determinant of Array M is: (5/2 - sqrt(33)/2)*(5/2 + sqrt(33)/2)


Second option:

In [ ]:
import numpy as np
from numpy.linalg import eig
  
try:
  numR = int(input("How many rows (ONLY ONE NUMBER):"))
  numC = int(input("How many columns (ONLY ONE NUMBER):"))
  numT = numR*numC
  
  if (numC == numR):
    print("Enter {0} entries in a single line (separated by space): ".format(numT))
    entries = list(map(int, input().split()))
    print(' ')
    
    if (len(entries) == numT):
      matrix = np.array(entries).reshape(numR, numC)
      M = matrix
      #print('M =',M)

      eigenvalues, eigenvectors = eig(M)
      print('Eigenvalues of array M: ',list(eigenvalues))
      print(' ')
       
    else:
      print('Enter {0} entries separated by a space'.format(numR*numC))

  else:
    print("Enter an identical integer value")
except ValueError:
  print("ENTER A NUMBER")

num = 1
for i in range(len(eigenvalues)):
  num *= eigenvalues[i]

print('Therefore determinant of Array M is: {0}'.format(round(num,2)))



How many rows (ONLY ONE NUMBER):2
How many columns (ONLY ONE NUMBER):2
Enter 4 entries in a single line (separated by space): 
1 2 3 4
 
Eigenvalues of array M:  [-0.3722813232690143, 5.372281323269014]
 
Therefore determinant of Array M is: -2.0
